### ISSUE TITLE
not work for Exception

### ISSUE THREAD

**Issue by Oxicode** [gourmet/whoops#12]
![image](https://cloud.githubusercontent.com/assets/1320709/22571088/2f88acee-e96c-11e6-92ca-9ccc7f26fae2.png)

![image](https://cloud.githubusercontent.com/assets/1320709/22571103/467ab0aa-e96c-11e6-96cf-3146985fa242.png)

**Comment by GabrielApG** [comment]
Mesmo problema.

**Comment by LDSign** [comment]
Any update on this?

**Comment by Equinoxlimited** [comment]
Because an exception is not an error.  If debug = true you will see the missing controller/view etc debug information. 

To change what displays you need to create a template in src/Template/Error/missing_controller.ctp or missing_view.ctp

<img width="1213" alt="screen shot 2017-10-20 at 3 00 12 pm" src="https://user-images.githubusercontent.com/19823200/31837764-fe28bb90-b5a7-11e7-86e7-9a5719efef3d.png">

**Comment by Oxicode** [comment]
nothing 
![image](https://user-images.githubusercontent.com/1320709/31840398-da4614ae-b5aa-11e7-9802-46e913b73e7a.png)

**Comment by dereuromark** [comment]
Are you using the new Middleware? that will be the reason then.
See the new repo https://github.com/dereuromark/cakephp-whoops - if you try that it should help you getting started here.

Exceptions are actually the **main** thing that should be covered by whoops :)
Because the rest is not for the dev, but for end users (and without debug mode then).
